package com.cg.ibs.accountmanagement.ui;

public enum CustomerMenu {
	CHECK_BALANCE,TRANSFER_FUNDS,GENERATE_MINI_STATEMENT,GENERATE_PERIODIC_STATEMENT,OPEN_ACCOUNT,VIEW_ACCOUNT,CLOSE_ACCOUNT,PAY_UTILITY_BILLS,QUIT ;
}
